builds:
  - id: dprc
    main: ./cmd/dprc
    binary: dprc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/Arthur1/dpr.Version={{.Version}}
  - id: dpr-cleaner-eventbridge-lambda
    main: ./cmd/dpr-cleaner-eventbridge-lambda
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X github.com/Arthur1/dpr.Version={{.Version}}

archives:
  - id: dprc
    format: tar.gz
    builds:
      - dprc
    name_template: >-
      dprc_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: dpr-cleaner-eventbridge-lambda
    format: zip
    builds:
      - dpr-cleaner-eventbridge-lambda
    name_template: dpr-cleaner-eventbridge-lambda
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: dprc
    ids:
      - dprc
    repository:
      owner: Arthur1
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
