name: CI for main branch

on:
  push:
    branches: [main]

jobs:
  test-go:
    uses: ./.github/workflows/wf-test-go.yml

  test-terraform:
    uses: ./.github/workflows/wf-test-terraform.yml

  build:
    uses: ./.github/workflows/wf-build.yml
