name: release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 364898
          private-key: ${{ secrets.ARTHUR1_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "dpr,homebrew-tap"
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
          distribution: goreleaser
          version: latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAP_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
